[package]
name = "wasm-component-ld"
version = "0.1.1"
edition = "2021"
license = "Apache-2.0 WITH LLVM-exception OR Apache-2.0 OR MIT"
description = "Linker for `wasm32-wasip2`"
repository = "https://github.com/alexcrichton/wasm-component-ld"
readme = "README.md"

[dependencies]
anyhow = "1.0.75"
clap = { version = "4.4.11", features = ["derive"] }
tempfile = "3.8.1"
wasmparser = "0.121.1"
wit-component = "0.20.2"
