[package]
name = "wasm-component-ld"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
clap = { version = "4.4.11", features = ["derive"] }
tempfile = "3.8.1"
wasmparser = "0.121.1"
wit-component = "0.20.2"
