[package]
name = "wasm-component-ld"
version = "0.2.0"
edition = "2021"
license = "Apache-2.0 WITH LLVM-exception OR Apache-2.0 OR MIT"
description = "Linker for `wasm32-wasip2`"
repository = "https://github.com/alexcrichton/wasm-component-ld"
readme = "README.md"

[dependencies]
anyhow = "1.0.80"
clap = { version = "4.5.4", features = ['derive'] }
lexopt = "0.3.0"
tempfile = "3.10.0"
wasmparser = "0.202.0"
wit-component = "0.202.0"
